name: freeswitch master build docker image

# release tag 时触发执行
on:
 push
 
jobs:
  build:
    # 运行在那个虚拟机之上
    runs-on: ubuntu-latest
    steps:
      # 获取dockerfile项目
      -
        name: Checkout
        uses: actions/checkout@v3
      # 获取dockerfile项目
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # 获取dockerfile项目
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # 获取dockerfile项目
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_TOKEN }}
      # 获取dockerfile项目
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: icerleer/freeswitchd:latest

    
